# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ff7d49a077f637fe8870180c97ab673469c59538a2939b9af30a6c36817ec53d51aa493275dc8b42ada4cd2bbd6225a5619db5f11b367ee7029cf2cbc5fcb1

test:
  secret_key_base: 6707731d9b23c8b5586ece6da7a50e9b0c9b48b01ee2ffda2768a2b3c70edf58897ae0e45b8b817ed3f92c06d1fd477c0cf1fcfb59259f27d1a3358e83a09896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
